# Generated by Django 4.1.2 on 2022-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('item_amount', models.CharField(max_length=20)),
                ('item_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
