# Generated by Django 4.1.2 on 2022-12-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0005_rename_first_name_customer_name_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
